// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACF06OMjoGp97SxLTQfnZs27zTql_r2aA',
    appId: '1:692167422939:web:df43499f86c85f334a2dfe',
    messagingSenderId: '692167422939',
    projectId: 'fast-food-app-f58ca',
    authDomain: 'fast-food-app-f58ca.firebaseapp.com',
    storageBucket: 'fast-food-app-f58ca.firebasestorage.app',
    measurementId: 'G-30K7R5CX7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4RWxHwNDs39XZa_GechXSrpoGDKXaT78',
    appId: '1:692167422939:android:c6e06447bc7330094a2dfe',
    messagingSenderId: '692167422939',
    projectId: 'fast-food-app-f58ca',
    storageBucket: 'fast-food-app-f58ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxAT7gdDT9tbsqIG2hQ1khGNpixJnK8tg',
    appId: '1:692167422939:ios:f8de7effb51abc1d4a2dfe',
    messagingSenderId: '692167422939',
    projectId: 'fast-food-app-f58ca',
    storageBucket: 'fast-food-app-f58ca.firebasestorage.app',
    iosBundleId: 'com.example.fastFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxAT7gdDT9tbsqIG2hQ1khGNpixJnK8tg',
    appId: '1:692167422939:ios:f8de7effb51abc1d4a2dfe',
    messagingSenderId: '692167422939',
    projectId: 'fast-food-app-f58ca',
    storageBucket: 'fast-food-app-f58ca.firebasestorage.app',
    iosBundleId: 'com.example.fastFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACF06OMjoGp97SxLTQfnZs27zTql_r2aA',
    appId: '1:692167422939:web:f4af0dc40ec29b304a2dfe',
    messagingSenderId: '692167422939',
    projectId: 'fast-food-app-f58ca',
    authDomain: 'fast-food-app-f58ca.firebaseapp.com',
    storageBucket: 'fast-food-app-f58ca.firebasestorage.app',
    measurementId: 'G-XZ05C84E1K',
  );
}
